import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Oswald } from "next/font/google";
import "./globals.css";

const barlow = Oswald({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "NordinDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className}  antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow flex flex-col bg-gray-100">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
